### ISSUE TITLE
常见错误汇总

### ISSUE THREAD

**Issue by LeeeeeeM** [quickappcn/quickapp-dsl-vue#9]
调试器闪退： 保证hap-toolkit版本号大于0.4.1
quickappp-dsls版本号大于0.1.1

build或者调试 命令行添加 --include-dsl-from-lib

**Comment by mengxuan763969190** [comment]
使用vue开发快应用 能支持  elementui框架引入吗
能的话能否告知怎么使用

**Comment by diydyq** [comment]
elementui是基于浏览器渲染和vue框架的组件库；
快应用目前底层用的是原生渲染，非浏览器环境，因为不支持这类组件库；
